name: py-codenames
channels:
  - defaults
dependencies:
  - python=3.6.8
  - pip=19.2.2
  - pip:
      - ipykernel==5.1.2
      - jupyter==1.0.0
      - fasttext==0.9.2
      - nltk==3.5
      - spacy==3.0.5
      - gensim==3.8.3
      - termcolor==1.1.0
      - pylint==2.13.9
